language: node_js
dist: xenial
node_js:
  - "4"
  - "8"
  - "10"
before_install:
  - chmod +x ./test/travis-before-install
  - ./test/travis-before-install
before_script:
  - chmod +x ./test/travis-before-script
  - ./test/travis-before-script
